<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Obituary;
use App\Models\Payment;
use Illuminate\Database\Seeder;

class ObituarySeeder extends Seeder
{
    public function run(): void
    {
        $admin = Admin::first();
        $today = now();

        $samples = [
            [
                'full_name' => 'Mzee Joseph Kiprop Cheruiyot',
                'slug' => 'mzee-joseph-kiprop-cheruiyot',
                'date_of_birth' => '1945-03-12',
                'date_of_death' => '2026-07-15',
                'county' => 'Uasin Gishu',
                'town' => 'Eldoret',
                'biography' => 'Mzee Joseph Kiprop Cheruiyot was a devoted father, community elder, and retired senior educator who impacted generations of students across Rift Valley. He passed away peacefully surrounded by family.',
                'funeral_date' => '2026-08-01',
                'burial_location' => 'Family Farm, Kapseret, Eldoret',
                'church_service_location' => 'AIC Milimani, Eldoret',
                'submitter_name' => 'David Cheruiyot',
                'submitter_phone' => '0712345678',
                'submitter_email' => 'david.cheruiyot@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified with son via phone confirmation.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Dr. Grace Wambui Njenga',
                'slug' => 'dr-grace-wambui-njenga',
                'date_of_birth' => '1962-08-20',
                'date_of_death' => '2026-07-20',
                'county' => 'Nairobi',
                'town' => 'Westlands',
                'biography' => 'Dr. Grace Wambui Njenga was a pioneer healthcare professional and researcher at Kenyatta National Hospital. Known for her boundless compassion, wisdom, and leadership in public health.',
                'funeral_date' => '2026-08-05',
                'burial_location' => 'Limuru Memorial Gardens, Kiambu',
                'church_service_location' => 'All Saints Cathedral, Nairobi',
                'submitter_name' => 'Dr. Peter Njenga',
                'submitter_phone' => '0722998877',
                'submitter_email' => 'peter.njenga@example.com',
                'relationship' => 'Spouse',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified with spouse Peter Njenga.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Mama Mary Achieng Otieno',
                'slug' => 'mama-mary-achieng-otieno',
                'date_of_birth' => '1950-11-04',
                'date_of_death' => $today->copy()->subYears(1)->format('Y-m-d'), // 1st Anniversary Today
                'county' => 'Kisumu',
                'town' => 'Kisumu Central',
                'biography' => 'Mama Mary Achieng Otieno lived a remarkable life centered on faith, family, and community empowerment. She leaves behind a cherished legacy of love, unity, and strength.',
                'funeral_date' => '2025-08-08',
                'burial_location' => 'Kombewa Village, Seme, Kisumu',
                'church_service_location' => 'St. Stephen’s Cathedral, Kisumu',
                'submitter_name' => 'Susan Otieno',
                'submitter_phone' => '0733112233',
                'submitter_email' => 'susan.o@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified with daughter Susan Otieno.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Hon. Stephen Mutua Musyoka',
                'slug' => 'hon-stephen-mutua-musyoka',
                'date_of_birth' => '1955-04-18',
                'date_of_death' => '2026-07-10',
                'county' => 'Machakos',
                'town' => 'Machakos Town',
                'biography' => 'Hon. Stephen Mutua Musyoka was a respected local leader, administrator, and philanthropist who dedicated 35 years to public service in Ukambani.',
                'funeral_date' => '2026-07-28',
                'burial_location' => 'Family Homestead, Kathiani, Machakos',
                'church_service_location' => 'AIC Town Church, Machakos',
                'submitter_name' => 'Charles Musyoka',
                'submitter_phone' => '0711223344',
                'submitter_email' => 'charles.m@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Elder Peter Kimani Karanja',
                'slug' => 'elder-peter-kimani-karanja',
                'date_of_birth' => '1948-09-25',
                'date_of_death' => '2026-07-18',
                'county' => 'Kiambu',
                'town' => 'Thika',
                'biography' => 'Elder Peter Kimani Karanja was a pillar of faith, successful businessman, and dedicated church elder at PCEA Thika. Beloved by all.',
                'funeral_date' => '2026-08-02',
                'burial_location' => 'Gatundu South, Kiambu',
                'church_service_location' => 'PCEA Thika Town Church',
                'submitter_name' => 'Mary Kimani',
                'submitter_phone' => '0722334455',
                'submitter_email' => 'mary.k@example.com',
                'relationship' => 'Spouse',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Mama Beatrice Nyambura Mwangi',
                'slug' => 'mama-beatrice-nyambura-mwangi',
                'date_of_birth' => '1958-01-14',
                'date_of_death' => $today->copy()->subYears(5)->format('Y-m-d'), // 5th Anniversary Today
                'county' => 'Nakuru',
                'town' => 'Naivasha',
                'biography' => 'Mama Beatrice Nyambura Mwangi was a cherished mother, teacher, and entrepreneur in Naivasha. Her warmth and guidance live forever in our hearts.',
                'funeral_date' => '2021-08-03',
                'burial_location' => 'Kinangop, Nyandarua',
                'church_service_location' => 'ACK St. Luke, Naivasha',
                'submitter_name' => 'John Mwangi',
                'submitter_phone' => '0733445566',
                'submitter_email' => 'john.mwangi@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Eng. Patrick Omondi Anyango',
                'slug' => 'eng-patrick-omondi-anyango',
                'date_of_birth' => '1970-06-30',
                'date_of_death' => '2026-07-22',
                'county' => 'Siaya',
                'town' => 'Bondo',
                'biography' => 'Eng. Patrick Omondi Anyango was a talented civil engineer who spearheaded key infrastructure development projects across Kenya. Rest in peace.',
                'funeral_date' => '2026-08-07',
                'burial_location' => 'Nyamira Village, Bondo, Siaya',
                'church_service_location' => 'ACK St. Peter’s, Bondo',
                'submitter_name' => 'Caroline Omondi',
                'submitter_phone' => '0744556677',
                'submitter_email' => 'caroline.o@example.com',
                'relationship' => 'Spouse',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Mama Agnes Jebet Kiptoo',
                'slug' => 'mama-agnes-jebet-kiptoo',
                'date_of_birth' => '1952-12-10',
                'date_of_death' => '2026-07-12',
                'county' => 'Nandi',
                'town' => 'Kapsabet',
                'biography' => 'Mama Agnes Jebet Kiptoo was a devoted matriarch, farmer, and church leader who served her community with grace and diligence.',
                'funeral_date' => '2026-07-30',
                'burial_location' => 'Kilibwoni, Nandi',
                'church_service_location' => 'SDA Church Kapsabet',
                'submitter_name' => 'Emmanuel Kiptoo',
                'submitter_phone' => '0755667788',
                'submitter_email' => 'emmanuel.k@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Mzee Francis Katana Karisa',
                'slug' => 'mzee-francis-katana-karisa',
                'date_of_birth' => '1942-05-05',
                'date_of_death' => '2026-07-14',
                'county' => 'Mombasa',
                'town' => 'Nyali',
                'biography' => 'Mzee Francis Katana Karisa was a veteran maritime administrator and community elder along the Kenyan coast. Forever remembered.',
                'funeral_date' => '2026-08-04',
                'burial_location' => 'Kaloleni, Kilifi',
                'church_service_location' => 'Catholic Cathedral, Mombasa',
                'submitter_name' => 'Joseph Karisa',
                'submitter_phone' => '0766778899',
                'submitter_email' => 'joseph.karisa@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Sister Sarah Wanjiku Njuguna',
                'slug' => 'sister-sarah-wanjiku-njuguna',
                'date_of_birth' => '1965-03-22',
                'date_of_death' => '2026-07-21',
                'county' => 'Nyeri',
                'town' => 'Nyeri Town',
                'biography' => 'Sister Sarah Wanjiku Njuguna was an inspirational teacher and choir director who touched many lives with her beautiful music and faith.',
                'funeral_date' => '2026-08-06',
                'burial_location' => 'Karatina, Nyeri',
                'church_service_location' => 'Consolata Cathedral, Nyeri',
                'submitter_name' => 'Paul Njuguna',
                'submitter_phone' => '0777889900',
                'submitter_email' => 'paul.n@example.com',
                'relationship' => 'Sibling',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Professor James Ochieng Akelo',
                'slug' => 'professor-james-ochieng-akelo',
                'date_of_birth' => '1951-10-15',
                'date_of_death' => '2026-07-16',
                'county' => 'Homa Bay',
                'town' => 'Oyugis',
                'biography' => 'Professor James Ochieng Akelo was a distinguished university don, author, and mentor to hundreds of scholars across Africa.',
                'funeral_date' => '2026-08-02',
                'burial_location' => 'Rachuonyo, Homa Bay',
                'church_service_location' => 'SDA Church Oyugis',
                'submitter_name' => 'Dr. Elizabeth Akelo',
                'submitter_phone' => '0788990011',
                'submitter_email' => 'elizabeth.a@example.com',
                'relationship' => 'Spouse',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
            [
                'full_name' => 'Mama Rosemary Kamba Mbatha',
                'slug' => 'mama-rosemary-kamba-mbatha',
                'date_of_birth' => '1960-07-07',
                'date_of_death' => '2026-07-19',
                'county' => 'Kitui',
                'town' => 'Kitui Central',
                'biography' => 'Mama Rosemary Kamba Mbatha was a dedicated businesswoman, mother, and church leader whose legacy of generosity will live on.',
                'funeral_date' => '2026-08-05',
                'burial_location' => 'Mutomo, Kitui',
                'church_service_location' => 'AIC Kitui Town',
                'submitter_name' => 'Grace Mbatha',
                'submitter_phone' => '0799001122',
                'submitter_email' => 'grace.m@example.com',
                'relationship' => 'Child',
                'family_permission_confirmed' => true,
                'status' => 'published',
                'verification_status' => 'verified',
                'verification_notes' => 'Verified by admin.',
                'verified_by' => $admin?->id,
                'verified_at' => now(),
            ],
        ];

        foreach ($samples as $sample) {
            $obituary = Obituary::firstOrCreate(['slug' => $sample['slug']], $sample);

            Payment::firstOrCreate(['obituary_id' => $obituary->id], [
                'phone_number' => '254712345678',
                'amount' => 500.00,
                'merchant_request_id' => 'MR-' . uniqid(),
                'checkout_request_id' => 'CR-' . uniqid(),
                'mpesa_receipt_number' => 'QGH' . rand(1000000, 9999999),
                'status' => 'completed',
                'result_code' => '0',
                'result_desc' => 'The service request is processed successfully.',
            ]);
        }
    }
}
